movie_project/movie_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='movie_app'
urlpatterns = [
    path('',views.index, name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update, name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie_project/movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_project/movie_app/forms.py
from django import forms
from .models import movies

class movieform(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','description','year','image']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import movieform
from .models import movies

# Create your views here.
def index(request):
    movie=movies.objects.all()
    context={
        "movie_list":movie
    }
    return render(request,'index.html',context)

def details(request,movie_id):
    movie=movies.objects.get(id=movie_id)
    return render(request,'details.html', {'movie': movie})

def add_movie(request):
    if request.method == "POST":
        name=request.POST.get('name')
        description=request.POST.get('description')
        year=request.POST.get('year')
        image=request.FILES['image']
        movie=movies(name=name,description=description,year=year,image=image)
        movie.save()

    return render(request,'add.html')


def update(request, id):
    movie=movies.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method =="POST":
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie_project/templates/add.html
{% extends 'base.html' %}

{% block body %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <h3>Add Movie</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" placeholder="Enter Movie Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="number" name="year" class="form-control" placeholder="Enter released date" value="" />
                        </div>
                      <div class="form-group">
                            <input type="file" name="image" >
                        </div>
                        <div class="form-group">
                         <input type="submit" class="btn btn-warning" value="ADD" ></input>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="description" class="form-control" placeholder="Enter Movie description" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>
<!--<form method="POST" enctype="multipart/form-data">-->

<!--  <input type="text" name="name" placeholder="ENTER MOVIE NAME">-->
<!--  <input type="text" name="description" placeholder="ENTER MOVIE DESCRIPTION">-->
<!--  <input type="number" name="year" placeholder="ENTER YEAR RELEASED">-->
<!--  -->
<!--  <input type="submit">-->

<!--</form>-->
{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Database</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie DB
  </a>
</nav>
</body>
</html>
{% block body %}
{% endblock %}

movie_project/templates/delete.html
{% extends 'base.html' %}

{% block body %}
<form method="POST">
  {% csrf_token %}

  Are you sure??
  <input type="submit">

</form>
{% endblock %}

movie_project/templates/details.html
{% extends 'base.html' %}

{% block body %}

<!--   -->

<section id="gallery">
  <div class="container">
    <div class="row">
    <div class="col-lg-6 mb-6">
    <div class="card">
      <img src="{{movie.image.url}}" alt="" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{movie.name}}</h5><br>
                  <h6 class="card-title">{{movie.year}}</h6>

        <p class="card-text">{{movie.description}}</p>
       <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>
      </div>
     </div>
    </div>


  </div>
</div>
</section>




{% endblock %}

movie_project/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<link href="{% static 'form.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}<br>
       <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>


    </form>
</div>


{% endblock %}

movie_project/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

 <head>
    <meta charset="utf-8">
    <title> home</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'boot.css'%}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>


    <div class="wrapper-grey padded">

      <div class="container">


          <div class="row">
               {% for i in movie_list %}
              <div class="col-md-3">

                 <div class="card" style="background:  url('{{i.image.url}}');">
                  <div class="card-description">
                    <h2>{{i.name}}</h2>
                    <p>{{i.year}}</p>
                  </div>
    <!--              <img class="card-user avatar avatar-large" src="">-->
              <a class="card-link" href="{% url 'movie_app:details' i.id %}" ></a>
            </div>

          </div>
<!--          <div class="col-xs-12 col-sm-4">-->
<!--            <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://i0.wp.com/handluggageonly.co.uk/wp-content/uploads/2016/04/IMG_5589.jpg?w=1600&ssl=1');">-->
<!--              <div class="card-category">City</div>-->
<!--              <div class="card-description">-->
<!--                <h2>home1</h2>-->
<!--                <p>Lovely house</p>-->
<!--              </div>-->
<!--              <img class="card-user avatar avatar-large" src="https://github.com/lewagon/bootstrap-challenges/blob/master/11-Airbnb-search-form/images/anne.jpg?raw=true">-->
<!--              <a class="card-link" href="#" ></a>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-xs-12 col-sm-4">-->
<!--            <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://i0.wp.com/handluggageonly.co.uk/wp-content/uploads/2016/03/Positano-Weather.jpg?w=1600&ssl=1');">-->
<!--              <div class="card-category">City</div>-->
<!--              <div class="card-description">-->
<!--                <h2>Home</h2>-->
<!--                <p>Lovely house</p>-->
<!--              </div>-->
<!--              <img class="card-user avatar avatar-large" src="https://github.com/lewagon/bootstrap-challenges/blob/master/11-Airbnb-search-form/images/anne.jpg?raw=true">-->
<!--              <a class="card-link" href="#" ></a>-->
<!--            </div>-->
<!--          </div>-->
              {% endfor %}
        </div>


      </div>

    </div>

    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>

<a href="">{{i.name}}<br>
{% endblock %}